import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className=' w-full h-8 border-solid border border-gray-400 text-center'>
        <h1>头部</h1>
      </div>
        {children}
      </body>
    </html>
  )
}
